-- 添加焦点位置字段到 photo 表
-- 执行时间: 2025-01-XX

ALTER TABLE `photo` 
ADD COLUMN IF NOT EXISTS `focus_x` DECIMAL(5,2) DEFAULT NULL COMMENT '焦点X位置（百分比 0-100）',
ADD COLUMN IF NOT EXISTS `focus_y` DECIMAL(5,2) DEFAULT NULL COMMENT '焦点Y位置（百分比 0-100）';


